source 'https://rubygems.org'

gem 'rails', '3.2.2'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'
gem 'active_attr', '>= 0.5.1'
gem 'slim-rails', '>= 1.0.3'
gem 'simple_form', '>= 2.0.0'
gem 'jquery-rails'
gem 'mixlib-log', '1.3.0'
gem 'yajl-ruby', '>= 1.1.0'
gem 'fog'
gem 'forgery'
gem 'cabin'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'twitter-bootstrap-rails', '>= 2.0.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :test do
  gem 'rspec-rails', '>= 2.9.0'
  gem 'cucumber-rails', '>= 1.3.0'
  gem 'factory_girl_rails', '>= 1.7.0'
  gem 'shoulda-matchers', '>= 1.0.0'
  gem 'capybara', '>= 1.1.2'
  gem 'rack-test', '>= 0.6.0', :require => 'rack/test'
  gem 'spork', '>= 1.0.0rc2'
  gem 'guard', '>= 1.0.0'
  gem 'guard-rails', '>= 0.1.0'
  gem 'guard-rspec', '>= 0.6.0'
  gem 'guard-spork', '>= 0.5.2'
  gem 'guard-bundler'
  gem 'rb-fsevent', '>= 0.9.0'
  gem 'growl', '>= 1.0.3'
  gem 'database_cleaner', '>= 0.7.1'
  gem 'tach'
  gem 'forgery'
  gem 'timecop'
end